# Generated by Django 4.2.1 on 2023-05-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_alter_personnel_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='gender',
            field=models.CharField(choices=[('Female', 'F'), ('Male', 'M'), ('Other', 'O'), ('Prefer Not Say', 'N')], max_length=19),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='title',
            field=models.CharField(choices=[('Senior', 'S'), ('Mid Senior', 'M'), ('Junior', 'J')], max_length=15),
        ),
    ]
