# Generated by Django 4.2.1 on 2023-05-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_alter_personnel_gender_alter_personnel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='gender',
            field=models.CharField(choices=[('Female', 'F'), ('Male', 'M'), ('Other', 'O'), ('Prefer Not Say', 'N')], max_length=19),
        ),
    ]
